Quote shell variables

diff --git a/check-xmllint b/check-xmllint
--- a/check-xmllint
+++ b/check-xmllint
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-XMLLINT=xmllint
+XMLLINT="xmllint"
 
 if [ -t 1 ]; then
   R=$(tput setaf 1)
@@ -37,25 +37,25 @@ retval=0
 
 for FILE in $*; do
   tmpfile=$(mktemp)
-  if ! $XMLLINT --format $FILE > $tmpfile; then
-      echo "XML check for $FILE: ${R}cannot parse${N}"
+  if ! "${XMLLINT}" --format "${FILE}" > "${tmpfile}"; then
+      echo "XML check for ${FILE}: ${R}cannot parse${N}"
       retval=1
   else
-    if ! diff $tmpfile $FILE; then
+    if ! diff "${tmpfile}" "${FILE}"; then
       if [ $inplace -eq 0 ]; then
-        echo "XML check for $FILE: ${R}failed${N}"
+        echo "XML check for ${FILE}: ${R}failed${N}"
         retval=2
       else
-        tmpfile=$(mktemp)
-        $XMLLINT --format $FILE > $tmpfile
-        cp $tmpfile $FILE
-        echo "XML check for $FILE: ${Y}reformatted${N}"
+        tmpfile="$(mktemp)"
+        "${XMLLINT}" --format "${FILE}" > "${tmpfile}"
+        cp "${tmpfile}" "${FILE}"
+        echo "XML check for ${FILE}: ${Y}reformatted${N}"
       fi
     else
-      echo "XML check for $FILE: ${G}OK${N}"
+      echo "XML check for ${FILE}: ${G}OK${N}"
     fi
   fi
-  rm -f $tmpfile
+  rm -f "${tmpfile}"
 done
 
-exit $retval
+exit "${retval}"
