enable all options

diff --git a/check-xmllint b/check-xmllint
--- a/check-xmllint
+++ b/check-xmllint
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-XMLLINT=xmllint
-
 if [ -t 1 ]; then
   R=$(tput setaf 1)
   G=$(tput setaf 2)
@@ -9,25 +7,39 @@ if [ -t 1 ]; then
   N=$(tput sgr0)
 fi
 
-args=$(getopt i $*)
-if [ $? -ne 0 ]; then
-  echo "Usage: check-xmllint [-i] <files..>
-  -i overwrite files with xmllint formatted content
-"
-  exit 2
-fi
-set -- $args
+args=""
+files=""
 
-inplace=0
+INPLACE=0
+FORMAT=0
 
-while true; do
+for OPT in "$@"
+do
   case "$1" in
-    -i)
-      inplace=1
+    --format)
+      FORMAT=1
+      args="${args} ${file} $1"
+      file=""
       ;;
-    --)
-      shift
-      break
+    --*)
+      for w in $(echo $1 | tr "=" " ")
+      do
+        args="${args} $w"
+      done
+      ;;
+    -i)
+      INPLACE=1
+      args="${args} ${file}"
+      file=""
+      ;;
+    -*)
+      for w in $(echo $1 | tr "=" " ")
+      do
+        args="${args} $w"
+      done
+      ;;
+    *)
+      files="${files} $1"
       ;;
   esac
   shift
@@ -35,24 +47,24 @@ done
 
 retval=0
 
-for FILE in $*; do
+for FILE in ${files}; do
   tmpfile=$(mktemp)
-  if ! $XMLLINT --format $FILE > $tmpfile; then
-      echo "XML check for $FILE: ${R}cannot parse${N}"
+  if ! xmllint ${args} $FILE > $tmpfile; then
+      echo "XML check for $FILE: ${R}cannot parse or mismatch schema${N}"
       retval=1
   else
-    if ! diff $tmpfile $FILE; then
-      if [ $inplace -eq 0 ]; then
-        echo "XML check for $FILE: ${R}failed${N}"
-        retval=2
+    if [ ${FORMAT} -eq 1 ]; then
+      if ! diff $tmpfile $FILE; then
+        if [ $INPLACE -eq 0 ]; then
+          echo "XML check for $FILE: ${R}failed${N}"
+          retval=2
+        else
+          cp $tmpfile $FILE
+          echo "XML check for $FILE: ${Y}reformatted${N}"
+        fi
       else
-        tmpfile=$(mktemp)
-        $XMLLINT --format $FILE > $tmpfile
-        cp $tmpfile $FILE
-        echo "XML check for $FILE: ${Y}reformatted${N}"
+        echo "XML check for $FILE: ${G}OK${N}"
       fi
-    else
-      echo "XML check for $FILE: ${G}OK${N}"
     fi
   fi
   rm -f $tmpfile
